create database Logistica;
use Logistica;


create table Entregador(
	ID_ENT BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TX_NOME_ENT VARCHAR(30),
	TX_TELEFONE_ENT VARCHAR(12),
	ATIVO BIT
);

CREATE TABLE VEICULO(
	ID_VEIC BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TX_PLACA_VEIC CHAR(7) UNIQUE,
	TIPO_VEIC INT,
	ID_ENT BIGINT NOT NULL,
	CONSTRAINT FK_TIP_VEIC FOREIGN KEY (TIPO_VEIC) REFERENCES TipoVeiculoEnum(ID_TIP),
	CONSTRAINT FK_ENT_VEIC FOREIGN KEY (ID_ENT) REFERENCES Entregador(ID_ENT)
	CONSTRAINT CK_Veiculo_Tipo CHECK (TipoVeiculo IN ('Moto', 'Carro', 'Bicicleta', 'Outro'))
);